{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "28fdbb8f",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.neighbors import NearestNeighbors\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "import sklearn\n",
    "from __future__ import print_function\n",
    "import librosa\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from librosa import display,core\n",
    "from dtw import dtw\n",
    "from numpy import linalg as LA\n",
    "from math import sqrt\n",
    "from scipy import stats\n",
    "from sklearn import svm\n",
    "from sklearn.svm import SVR\n",
    "from mlxtend.plotting import plot_decision_regions\n",
    "import matplotlib.patches as mpatches\n",
    "from sklearn.model_selection import cross_val_predict, cross_val_score,cross_validate\n",
    "from sklearn import metrics\n",
    "from sklearn.mixture import GaussianMixture\n",
    "from sklearn.model_selection import train_test_split\n",
    "#%matplotlib inline\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from mlxtend.plotting import plot_confusion_matrix\n",
    "from collections import Counter\n",
    "from sklearn.metrics import confusion_matrix\n",
    "\n",
    "from imblearn.over_sampling import RandomOverSampler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "17c63342",
   "metadata": {},
   "outputs": [],
   "source": [
    "def accuracy(prediction,actual):\n",
    "    count=0\n",
    "    l=len(prediction)\n",
    "    for i in range(l):\n",
    "        if(prediction[i]==actual[i]):\n",
    "            count+=1\n",
    "    return count/l*100"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "2999c009",
   "metadata": {},
   "outputs": [],
   "source": [
    "import librosa\n",
    "import numpy as np\n",
    "from sklearn.model_selection import train_test_split\n",
    "import os\n",
    "\n",
    "def createTrainingData(start, end):\n",
    "    samples = []\n",
    "    telangana_dir = 'audio/Telangana'\n",
    "    coastal_dir = 'audio/Coastal'\n",
    "    rayalseema_dir = 'audio/Rayalseema'\n",
    "    \n",
    "    regions = {\n",
    "        'Telangana': telangana_dir,\n",
    "        'Coastal': coastal_dir,\n",
    "        'Rayalseema':rayalseema_dir\n",
    "    }\n",
    "\n",
    "    for region, region_dir in regions.items():\n",
    "        if region == 'Telangana':\n",
    "            file_range = range(239, 357)\n",
    "        elif region == 'Rayalseema':\n",
    "            file_range = range(116, 215)\n",
    "        elif region == 'Coastal':\n",
    "            file_range = range(1, 102)  # Assuming audio files in Coastal are named from '1.wav' to '101.wav'\n",
    "\n",
    "        for i in file_range:\n",
    "            ind = 0\n",
    "            try:\n",
    "                file_path = os.path.join(region_dir, f\"{i}.wav\")\n",
    "                a, s = librosa.load(file_path)\n",
    "            except:\n",
    "                ind = 1\n",
    "\n",
    "            if ind == 0:\n",
    "                mfcc = librosa.feature.mfcc(y=a, sr=s)\n",
    "                temp = mfcc.T[1][start:end]\n",
    "                for frame in range(10, 50):\n",
    "                    temp = np.concatenate((temp, mfcc.T[frame][start:end]))\n",
    "                samples.append([temp, region])\n",
    "\n",
    "    print(len(samples))\n",
    "    X = [i[0] for i in samples]\n",
    "    Y = [j[1] for j in samples]\n",
    "    return X, Y\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "575102e0",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\cluster\\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 115, in __call__\n",
      "    score = scorer._score(cached_call, estimator, *args, **kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 282, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1146, in f1_score\n",
      "    return fbeta_score(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1287, in fbeta_score\n",
      "    _, _, f, _ = precision_recall_fscore_support(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1573, in precision_recall_fscore_support\n",
      "    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1377, in _check_set_wise_labels\n",
      "    present_labels = unique_labels(y_true, y_pred).tolist()\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 117, in unique_labels\n",
      "    raise ValueError(\"Mix of label input types (string and number)\")\n",
      "ValueError: Mix of label input types (string and number)\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\cluster\\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 115, in __call__\n",
      "    score = scorer._score(cached_call, estimator, *args, **kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 282, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1146, in f1_score\n",
      "    return fbeta_score(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1287, in fbeta_score\n",
      "    _, _, f, _ = precision_recall_fscore_support(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1573, in precision_recall_fscore_support\n",
      "    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1377, in _check_set_wise_labels\n",
      "    present_labels = unique_labels(y_true, y_pred).tolist()\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 117, in unique_labels\n",
      "    raise ValueError(\"Mix of label input types (string and number)\")\n",
      "ValueError: Mix of label input types (string and number)\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\cluster\\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 115, in __call__\n",
      "    score = scorer._score(cached_call, estimator, *args, **kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 282, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1146, in f1_score\n",
      "    return fbeta_score(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1287, in fbeta_score\n",
      "    _, _, f, _ = precision_recall_fscore_support(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1573, in precision_recall_fscore_support\n",
      "    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1377, in _check_set_wise_labels\n",
      "    present_labels = unique_labels(y_true, y_pred).tolist()\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 117, in unique_labels\n",
      "    raise ValueError(\"Mix of label input types (string and number)\")\n",
      "ValueError: Mix of label input types (string and number)\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\cluster\\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 115, in __call__\n",
      "    score = scorer._score(cached_call, estimator, *args, **kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 282, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1146, in f1_score\n",
      "    return fbeta_score(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1287, in fbeta_score\n",
      "    _, _, f, _ = precision_recall_fscore_support(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1573, in precision_recall_fscore_support\n",
      "    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1377, in _check_set_wise_labels\n",
      "    present_labels = unique_labels(y_true, y_pred).tolist()\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 117, in unique_labels\n",
      "    raise ValueError(\"Mix of label input types (string and number)\")\n",
      "ValueError: Mix of label input types (string and number)\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\cluster\\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 115, in __call__\n",
      "    score = scorer._score(cached_call, estimator, *args, **kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 282, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1146, in f1_score\n",
      "    return fbeta_score(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1287, in fbeta_score\n",
      "    _, _, f, _ = precision_recall_fscore_support(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1573, in precision_recall_fscore_support\n",
      "    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1377, in _check_set_wise_labels\n",
      "    present_labels = unique_labels(y_true, y_pred).tolist()\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 117, in unique_labels\n",
      "    raise ValueError(\"Mix of label input types (string and number)\")\n",
      "ValueError: Mix of label input types (string and number)\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\cluster\\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 115, in __call__\n",
      "    score = scorer._score(cached_call, estimator, *args, **kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 282, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1146, in f1_score\n",
      "    return fbeta_score(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1287, in fbeta_score\n",
      "    _, _, f, _ = precision_recall_fscore_support(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1573, in precision_recall_fscore_support\n",
      "    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1377, in _check_set_wise_labels\n",
      "    present_labels = unique_labels(y_true, y_pred).tolist()\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 117, in unique_labels\n",
      "    raise ValueError(\"Mix of label input types (string and number)\")\n",
      "ValueError: Mix of label input types (string and number)\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\cluster\\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 115, in __call__\n",
      "    score = scorer._score(cached_call, estimator, *args, **kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 282, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1146, in f1_score\n",
      "    return fbeta_score(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1287, in fbeta_score\n",
      "    _, _, f, _ = precision_recall_fscore_support(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1573, in precision_recall_fscore_support\n",
      "    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1377, in _check_set_wise_labels\n",
      "    present_labels = unique_labels(y_true, y_pred).tolist()\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 117, in unique_labels\n",
      "    raise ValueError(\"Mix of label input types (string and number)\")\n",
      "ValueError: Mix of label input types (string and number)\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\cluster\\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 115, in __call__\n",
      "    score = scorer._score(cached_call, estimator, *args, **kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 282, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1146, in f1_score\n",
      "    return fbeta_score(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1287, in fbeta_score\n",
      "    _, _, f, _ = precision_recall_fscore_support(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1573, in precision_recall_fscore_support\n",
      "    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1377, in _check_set_wise_labels\n",
      "    present_labels = unique_labels(y_true, y_pred).tolist()\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 117, in unique_labels\n",
      "    raise ValueError(\"Mix of label input types (string and number)\")\n",
      "ValueError: Mix of label input types (string and number)\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\cluster\\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 115, in __call__\n",
      "    score = scorer._score(cached_call, estimator, *args, **kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 282, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1146, in f1_score\n",
      "    return fbeta_score(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1287, in fbeta_score\n",
      "    _, _, f, _ = precision_recall_fscore_support(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1573, in precision_recall_fscore_support\n",
      "    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1377, in _check_set_wise_labels\n",
      "    present_labels = unique_labels(y_true, y_pred).tolist()\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 117, in unique_labels\n",
      "    raise ValueError(\"Mix of label input types (string and number)\")\n",
      "ValueError: Mix of label input types (string and number)\n",
      "\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\cluster\\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.\n",
      "  warnings.warn(\n",
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 115, in __call__\n",
      "    score = scorer._score(cached_call, estimator, *args, **kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 282, in _score\n",
      "    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1146, in f1_score\n",
      "    return fbeta_score(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1287, in fbeta_score\n",
      "    _, _, f, _ = precision_recall_fscore_support(\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1573, in precision_recall_fscore_support\n",
      "    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1377, in _check_set_wise_labels\n",
      "    present_labels = unique_labels(y_true, y_pred).tolist()\n",
      "  File \"C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 117, in unique_labels\n",
      "    raise ValueError(\"Mix of label input types (string and number)\")\n",
      "ValueError: Mix of label input types (string and number)\n",
      "\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "(nan, nan)"
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "g = GaussianMixture(2)\n",
    "scores = cross_val_score(g, data, label, cv=10, scoring='f1_macro')\n",
    "scores.mean(),scores.std()  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "03c40d94",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[('Coastal', 89), ('Rayalseema', 89), ('Telangana', 89)]\n"
     ]
    }
   ],
   "source": [
    "X_train, X_test, y_train, y_test  = train_test_split(data,label)\n",
    "ros = RandomOverSampler(random_state=0)\n",
    "X_resampled, y_resampled = ros.fit_resample(X_train, y_train)\n",
    "print(sorted(Counter(y_resampled).items()))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "9461e353",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\sklearn\\cluster\\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "g = GaussianMixture(2)\n",
    "g.fit(X_resampled)\n",
    "pred = g.predict(X_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "b60325fd",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 0, 19,  0],\n",
       "       [ 2, 30,  0],\n",
       "       [ 1, 28,  0]], dtype=int64)"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from sklearn.preprocessing import LabelEncoder\n",
    "\n",
    "# Initialize the label encoder\n",
    "label_encoder = LabelEncoder()\n",
    "\n",
    "# Fit the label encoder on the unique labels in y_test\n",
    "label_encoder.fit(y_test)\n",
    "\n",
    "# Transform y_test to numeric labels\n",
    "y_test_numeric = label_encoder.transform(y_test)\n",
    "\n",
    "# Now, you can calculate the confusion matrix\n",
    "conf_matrix = confusion_matrix(y_test_numeric, pred)\n",
    "conf_matrix"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "45367e2f",
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "Mix of label input types (string and number)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[20], line 3\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01msklearn\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmetrics\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m confusion_matrix\n\u001b[1;32m----> 3\u001b[0m conf_matrix \u001b[38;5;241m=\u001b[39m \u001b[43mconfusion_matrix\u001b[49m\u001b[43m(\u001b[49m\u001b[43my_test\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mpred\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m      5\u001b[0m \u001b[38;5;66;03m# Access the elements of the confusion matrix\u001b[39;00m\n\u001b[0;32m      6\u001b[0m tn \u001b[38;5;241m=\u001b[39m conf_matrix[\u001b[38;5;241m0\u001b[39m, \u001b[38;5;241m0\u001b[39m]  \u001b[38;5;66;03m# True negatives\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\sklearn\\metrics\\_classification.py:322\u001b[0m, in \u001b[0;36mconfusion_matrix\u001b[1;34m(y_true, y_pred, labels, sample_weight, normalize)\u001b[0m\n\u001b[0;32m    319\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m is not supported\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;241m%\u001b[39m y_type)\n\u001b[0;32m    321\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m labels \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m--> 322\u001b[0m     labels \u001b[38;5;241m=\u001b[39m \u001b[43munique_labels\u001b[49m\u001b[43m(\u001b[49m\u001b[43my_true\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43my_pred\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    323\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    324\u001b[0m     labels \u001b[38;5;241m=\u001b[39m np\u001b[38;5;241m.\u001b[39masarray(labels)\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py:117\u001b[0m, in \u001b[0;36munique_labels\u001b[1;34m(*ys)\u001b[0m\n\u001b[0;32m    115\u001b[0m \u001b[38;5;66;03m# Check that we don't mix string type with number type\u001b[39;00m\n\u001b[0;32m    116\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(\u001b[38;5;28mset\u001b[39m(\u001b[38;5;28misinstance\u001b[39m(label, \u001b[38;5;28mstr\u001b[39m) \u001b[38;5;28;01mfor\u001b[39;00m label \u001b[38;5;129;01min\u001b[39;00m ys_labels)) \u001b[38;5;241m>\u001b[39m \u001b[38;5;241m1\u001b[39m:\n\u001b[1;32m--> 117\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mMix of label input types (string and number)\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m    119\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m xp\u001b[38;5;241m.\u001b[39masarray(\u001b[38;5;28msorted\u001b[39m(ys_labels))\n",
      "\u001b[1;31mValueError\u001b[0m: Mix of label input types (string and number)"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import confusion_matrix\n",
    "\n",
    "conf_matrix = confusion_matrix(y_test, pred)\n",
    "\n",
    "# Access the elements of the confusion matrix\n",
    "tn = conf_matrix[0, 0]  # True negatives\n",
    "fp = conf_matrix[0, 1]  # False positives\n",
    "fn = conf_matrix[1, 0]  # False negatives\n",
    "tp = conf_matrix[1, 1]  # True positives\n",
    "conf_matrix"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eb248d59",
   "metadata": {},
   "outputs": [],
   "source": [
    "precision = round(tp/(tp+fp),4)\n",
    "recall = round(tp/(tp+fn),4)\n",
    "fmeasure = round(2*((precision*recall)/(precision+recall)),4)\n",
    "rej = round(tn/(tn+fp),4)\n",
    "acc = round((tn+tp)/(tn+tp+fp+fn),4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "207ed05d",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(precision,recall,fmeasure,rej,acc)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a1be99b7",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.metrics import roc_curve, auc\n",
    "from sklearn.preprocessing import label_binarize\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Assuming 'y_test' and 'pred' contain your actual labels and predicted labels\n",
    "# Convert labels to binary (0 and 1) for one-vs-all ROC AUC curve\n",
    "y_test_bin = label_binarize(y_test, classes=['Coastal', 'Rayalseema', 'Telangana'])\n",
    "pred_bin = label_binarize(pred, classes=['Coastal', 'Rayalseema', 'Telangana'])\n",
    "\n",
    "n_classes = y_test_bin.shape[1]\n",
    "\n",
    "# Initialize variables to store the ROC curve and AUC values\n",
    "fpr = dict()\n",
    "tpr = dict()\n",
    "roc_auc = dict()\n",
    "\n",
    "for i in range(n_classes):\n",
    "    fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], pred_bin[:, i])\n",
    "    roc_auc[i] = auc(fpr[i], tpr[i])\n",
    "\n",
    "# Plot the ROC AUC curves\n",
    "plt.figure(figsize=(10, 6))\n",
    "colors = ['b', 'g', 'r']\n",
    "for i, color in zip(range(n_classes), colors):\n",
    "    plt.plot(fpr[i], tpr[i], color=color, lw=2, label=f'ROC curve (area = {roc_auc[i]:0.2f}) for class {i}')\n",
    "\n",
    "plt.plot([0, 1], [0, 1], 'k--', lw=2)\n",
    "plt.xlim([0.0, 1.0])\n",
    "plt.ylim([0.0, 1.05])\n",
    "plt.xlabel('False Positive Rate')\n",
    "plt.ylabel('True Positive Rate')\n",
    "plt.title('Receiver Operating Characteristic (ROC) Curve')\n",
    "plt.legend(loc='lower right')\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "4f47fb75",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Lavanya Tetakali\\AppData\\Local\\Temp\\ipykernel_26984\\147644127.py:11: UserWarning: PySoundFile failed. Trying audioread instead.\n",
      "  audio, sample_rate = librosa.load(audio_path, res_type='kaiser_fast')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing audio\\.ipynb_checkpoints\\Untitled-checkpoint.ipynb: \n",
      "Error processing audio\\Coastal\\1.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\10.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\101.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\11.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\12.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\13.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\14.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\15.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\16.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\17.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\18.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\19.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\2.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\20.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\21.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\22.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\23.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\24.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\25.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\26.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\27.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\28.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\29.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\3.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\30.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\31.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\32.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\33.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\34.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\35.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\36.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\37.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\38.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\39.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\4.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\40.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\41.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\42.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\43.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\44.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing audio\\Coastal\\45.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\46.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\47.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\48.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\49.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\5.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\50.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\51.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\52.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\53.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\54.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\55.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\56.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\57.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\58.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\59.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\6.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\60.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\61.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\62.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\63.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\64.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\65.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\66.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\67.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\68.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\69.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\7.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\70.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\71.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\72.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\73.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\74.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\75.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\76.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\77.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\78.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\79.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\8.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\80.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\81.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\82.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\83.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\84.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\85.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\86.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\87.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\88.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\89.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\9.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\90.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\91.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\92.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\93.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\94.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\95.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\96.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\97.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\98.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\99.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Coastal\\README.md: \n",
      "Error processing audio\\Rayalseema\\116.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\117.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\118.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing audio\\Rayalseema\\119.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\120.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\121.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\122.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\123.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\124.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\125.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\126.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\127.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\128.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\129.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\130.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\131.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\132.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\133.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\134.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\135.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\136.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\137.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\138.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\139.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\140.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\141.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\142.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\143.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\144.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\145.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\146.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\147.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\148.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\149.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\150.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\151.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\152.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\153.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\154.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\155.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\156.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\157.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing audio\\Rayalseema\\158.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\159.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\160.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\161.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\162.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\163.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\164.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\165.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\166.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\167.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\168.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\169.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\170.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\171.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\172.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\173.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\174.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\175.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\176.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\177.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\178.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\179.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\180.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\181.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\182.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\183.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\184.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\185.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\186.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\187.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\188.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\189.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\190.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\191.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\192.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\193.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\194.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\195.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\196.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\197.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\198.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\199.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\200.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\201.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing audio\\Rayalseema\\202.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\203.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\204.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\205.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\206.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\207.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\208.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\209.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\210.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\211.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\212.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\213.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\214.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\215.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Rayalseema\\README.md: \n",
      "Error processing audio\\Telangana\\239.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\240.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\241.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\242.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\243.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\244.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\245.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\246.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\247.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\248.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\249.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\250.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\251.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\252.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\253.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\254.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\255.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\256.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\257.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\258.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\259.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\260.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\261.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\262.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\263.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing audio\\Telangana\\264.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\265.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\266.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\267.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\268.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\269.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\270.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\271.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\272.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\273.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\274.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\275.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\276.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\277.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\278.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\279.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\280.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\281.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\282.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\283.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\284.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\285.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\286.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\287.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\288.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\289.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\290.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\291.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\292.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\293.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\294.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\295.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\296.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\297.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\298.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\299.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\300.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\301.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\302.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\303.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\304.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\305.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\306.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\307.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\308.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\309.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\310.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\311.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\312.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\313.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\314.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\315.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\316.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\317.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\318.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\319.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\320.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\321.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\322.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\323.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\324.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\325.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\326.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\327.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\328.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing audio\\Telangana\\329.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\330.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\331.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\332.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\333.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\334.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\335.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\336.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\337.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\338.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\339.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\340.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\341.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\342.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\343.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\344.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\345.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\346.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\347.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\348.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\349.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\350.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\351.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\352.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\353.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\354.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\355.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\356.wav: No module named 'resampy'\n",
      "\n",
      "This error is lazily reported, having originally occured in\n",
      "  File C:\\Users\\Lavanya Tetakali\\anaconda3\\lib\\site-packages\\librosa\\core\\audio.py, line 32, in <module>\n",
      "\n",
      "----> resampy = lazy.load(\"resampy\")\n",
      "Error processing audio\\Telangana\\README.md: \n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[36], line 43\u001b[0m\n\u001b[0;32m     40\u001b[0m X, Y \u001b[38;5;241m=\u001b[39m load_and_preprocess_data(data_dir)\n\u001b[0;32m     42\u001b[0m \u001b[38;5;66;03m# Split the data into training and testing sets\u001b[39;00m\n\u001b[1;32m---> 43\u001b[0m X_train, X_test, y_train, y_test \u001b[38;5;241m=\u001b[39m \u001b[43mtrain_test_split\u001b[49m\u001b[43m(\u001b[49m\u001b[43mX\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mY\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtest_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m0.2\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mrandom_state\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m42\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[0;32m     45\u001b[0m \u001b[38;5;66;03m# Flatten the features to fit GMM\u001b[39;00m\n\u001b[0;32m     46\u001b[0m X_train \u001b[38;5;241m=\u001b[39m [item \u001b[38;5;28;01mfor\u001b[39;00m sublist \u001b[38;5;129;01min\u001b[39;00m X_train \u001b[38;5;28;01mfor\u001b[39;00m item \u001b[38;5;129;01min\u001b[39;00m sublist]\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_split.py:2562\u001b[0m, in \u001b[0;36mtrain_test_split\u001b[1;34m(test_size, train_size, random_state, shuffle, stratify, *arrays)\u001b[0m\n\u001b[0;32m   2559\u001b[0m arrays \u001b[38;5;241m=\u001b[39m indexable(\u001b[38;5;241m*\u001b[39marrays)\n\u001b[0;32m   2561\u001b[0m n_samples \u001b[38;5;241m=\u001b[39m _num_samples(arrays[\u001b[38;5;241m0\u001b[39m])\n\u001b[1;32m-> 2562\u001b[0m n_train, n_test \u001b[38;5;241m=\u001b[39m \u001b[43m_validate_shuffle_split\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m   2563\u001b[0m \u001b[43m    \u001b[49m\u001b[43mn_samples\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtest_size\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtrain_size\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdefault_test_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m0.25\u001b[39;49m\n\u001b[0;32m   2564\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   2566\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m shuffle \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mFalse\u001b[39;00m:\n\u001b[0;32m   2567\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m stratify \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_split.py:2236\u001b[0m, in \u001b[0;36m_validate_shuffle_split\u001b[1;34m(n_samples, test_size, train_size, default_test_size)\u001b[0m\n\u001b[0;32m   2233\u001b[0m n_train, n_test \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mint\u001b[39m(n_train), \u001b[38;5;28mint\u001b[39m(n_test)\n\u001b[0;32m   2235\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m n_train \u001b[38;5;241m==\u001b[39m \u001b[38;5;241m0\u001b[39m:\n\u001b[1;32m-> 2236\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[0;32m   2237\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mWith n_samples=\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m, test_size=\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m and train_size=\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m, the \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   2238\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mresulting train set will be empty. Adjust any of the \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   2239\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124maforementioned parameters.\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(n_samples, test_size, train_size)\n\u001b[0;32m   2240\u001b[0m     )\n\u001b[0;32m   2242\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m n_train, n_test\n",
      "\u001b[1;31mValueError\u001b[0m: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters."
     ]
    }
   ],
   "source": [
    "import os\n",
    "import librosa\n",
    "import numpy as np\n",
    "from sklearn.mixture import GaussianMixture\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import accuracy_score\n",
    "\n",
    "# Function to extract MFCC features from audio\n",
    "def extract_features(audio_path):\n",
    "    try:\n",
    "        audio, sample_rate = librosa.load(audio_path, res_type='kaiser_fast')\n",
    "        mfccs = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=13)\n",
    "        return mfccs\n",
    "    except Exception as e:\n",
    "        print(f\"Error processing {audio_path}: {e}\")\n",
    "        return None\n",
    "\n",
    "# Load and preprocess the audio data\n",
    "def load_and_preprocess_data(data_dir):\n",
    "    X = []  # Features\n",
    "    Y = []  # Labels\n",
    "\n",
    "    regions = os.listdir(data_dir)\n",
    "    for region in regions:\n",
    "        region_dir = os.path.join(data_dir, region)\n",
    "        if os.path.isdir(region_dir):  # Check if it's a directory\n",
    "            for filename in os.listdir(region_dir):\n",
    "                audio_path = os.path.join(region_dir, filename)\n",
    "                mfccs = extract_features(audio_path)\n",
    "                if mfccs is not None:\n",
    "                    X.append(mfccs)\n",
    "                    Y.append(region)\n",
    "\n",
    "    return X, Y\n",
    "\n",
    "# Specify the path to your audio data directory\n",
    "data_dir = 'audio'\n",
    "\n",
    "# Load and preprocess the data\n",
    "X, Y = load_and_preprocess_data(data_dir)\n",
    "\n",
    "# Split the data into training and testing sets\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)\n",
    "\n",
    "# Flatten the features to fit GMM\n",
    "X_train = [item for sublist in X_train for item in sublist]\n",
    "X_test = [item for sublist in X_test for item in sublist]\n",
    "\n",
    "# Train a Gaussian Mixture Model (GMM)\n",
    "n_components = 3  # You can adjust the number of components as needed\n",
    "gmm = GaussianMixture(n_components=n_components)\n",
    "gmm.fit(X_train)\n",
    "\n",
    "# Predict labels for the test set\n",
    "predictions = gmm.predict(X_test)\n",
    "\n",
    "# Calculate and print accuracy\n",
    "accuracy = accuracy_score(y_test, predictions)\n",
    "print(\"Accuracy:\", accuracy)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "c1c29c14",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting resampyNote: you may need to restart the kernel to use updated packages.\n",
      "\n",
      "  Downloading resampy-0.4.2-py3-none-any.whl (3.1 MB)\n",
      "     ---------------------------------------- 3.1/3.1 MB 2.5 MB/s eta 0:00:00\n",
      "Requirement already satisfied: numpy>=1.17 in c:\\users\\lavanya tetakali\\anaconda3\\lib\\site-packages (from resampy) (1.23.5)\n",
      "Requirement already satisfied: numba>=0.53 in c:\\users\\lavanya tetakali\\anaconda3\\lib\\site-packages (from resampy) (0.56.4)\n",
      "Requirement already satisfied: setuptools in c:\\users\\lavanya tetakali\\anaconda3\\lib\\site-packages (from numba>=0.53->resampy) (65.6.3)\n",
      "Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in c:\\users\\lavanya tetakali\\anaconda3\\lib\\site-packages (from numba>=0.53->resampy) (0.39.1)\n",
      "Installing collected packages: resampy\n",
      "Successfully installed resampy-0.4.2\n"
     ]
    }
   ],
   "source": [
    "pip install resampy\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
